Use cabal new-build in .travis.yml

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,306 +1,116 @@
-# This file has been generated by travis-meta-yaml 0.2.0.0
-# see https://github.com/phadej/travis-meta-yaml
-sudo: false
+# This Travis job script has been generated by a script via
+#
+#   make_travis_yml_2.hs 'servant-swagger-ui.cabal'
+#
+# For more information, see https://github.com/hvr/multi-ghc-travis
+#
 language: c
-before_install:
-- unset CC
-- export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
-- echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo
-  '?')]"
-- cabal --version
-- ghc --version
-- if [ "$NOTESTS" = "YES" ]; then export CABALCONFOPTS="$CABALFLAGS"; export CABALTEST="true";
-  else export CABALCONFOPTS="$CABALFLAGS --enable-tests --enable-benchmarks"; export
-  CABALTEST="cabal test"; fi
-- if [ "$PEDANTIC" = "YES" ]; then export CABALBUILDOPTS="--ghc-options=-Werror --ghc-options=-Wall";
-  fi
-install:
-- if [ -f $HOME/.cabal/packages/hackage.haskell.org/00-index.tar.gz ]; then zcat $HOME/.cabal/packages/hackage.haskell.org/00-index.tar.gz
-  > $HOME/.cabal/packages/hackage.haskell.org/00-index.tar; ls -l $HOME/.cabal/packages/hackage.haskell.org/;
-  fi; cabal update; sed -i 's/^jobs:/-- jobs:/' ${HOME}/.cabal/config; if [ -n "$CABALCONFIG"
-  ]; then cp $CABALCONFIG cabal.config; fi; if [ -n "$STACKAGESNAPSHOT" ]; then curl
-  --silent https://www.stackage.org/$STACKAGESNAPSHOT/cabal.config | grep -v "$(cabal
-  info . -v0 | head -n 1 | awk '{ print $2 }' | sed -E 's/-[0-9]+(\.[0-9]+)+//') =="
-  > cabal.config; fi; cabal install --constraint='integer-simple installed' --only-dependencies
-  $CABALCONFOPTS --dry -v > installplan.txt; sed -i -e '1,/^Resolving /d' installplan.txt;
-  cat installplan.txt; if diff -u $HOME/.cabsnap/installplan.txt installplan.txt;
-  then echo "cabal build-cache HIT"; rm -rfv .ghc; cp -av $HOME/.cabsnap/ghc $HOME/.ghc;
-  cp -av $HOME/.cabsnap/lib $HOME/.cabsnap/share $HOME/.cabsnap/bin $HOME/.cabal/;
-  else echo "cabal build-cache MISS"; rm -rf $HOME/.cabsnap; mkdir -p $HOME/.ghc $HOME/.cabal/lib
-  $HOME/.cabal/share $HOME/.cabal/bin; cabal install --constraint='integer-simple
-  installed' --only-dependencies $CABALCONFOPTS; fi; if [ ! -d $HOME/.cabsnap ]; then
-  echo "snapshotting package-db to build-cache"; mkdir $HOME/.cabsnap; cp -av $HOME/.ghc
-  $HOME/.cabsnap/ghc; cp -av $HOME/.cabal/lib $HOME/.cabal/share $HOME/.cabal/bin
-  installplan.txt $HOME/.cabsnap/; fi;
-script:
-- if [ -f configure.ac ]; then autoreconf -i; fi
-- cabal configure $CABALCONFOPTS -v2
-- cabal build $CABALBUILDOPTS
-- $CABALTEST
-- if [ "$CABALVER" = "1.22" ]; then cabal check; fi
-- cabal sdist
-- SRC_TGZ=$(cabal info . | awk '{print $2;exit}').tar.gz && (cd dist && cabal install
-  --constraint='integer-simple installed' --force-reinstalls $CABALFLAGS "$SRC_TGZ")
-matrix:
-  fast_finish: true
-  include:
-  - env: GHCVER=8.0.2 CABALVER=1.24 CABALCONFIG=swagger2-2.1-cabal.config
-    addons:
-      apt:
-        sources:
-        - hvr-ghc
-        packages:
-        - cabal-install-1.24
-        - ghc-8.0.2
-        - libgmp-dev
-    compiler: ! ': # ghc-8.0.2 cabal-1.24  swagger2-2.1-cabal.config'
-  - env: GHCVER=8.0.2 CABALVER=1.24 CABALCONFIG=servant-0.10-cabal.config
-    addons:
-      apt:
-        sources:
-        - hvr-ghc
-        packages:
-        - cabal-install-1.24
-        - ghc-8.0.2
-        - libgmp-dev
-    compiler: ! ': # ghc-8.0.2 cabal-1.24  servant-0.10-cabal.config'
-  - env: GHCVER=8.0.2 CABALVER=1.24 CABALCONFIG=servant-0.9-cabal.config
-    addons:
-      apt:
-        sources:
-        - hvr-ghc
-        packages:
-        - cabal-install-1.24
-        - ghc-8.0.2
-        - libgmp-dev
-    compiler: ! ': # ghc-8.0.2 cabal-1.24  servant-0.9-cabal.config'
-  - env: GHCVER=8.0.2 CABALVER=1.24 CABALCONFIG=servant-0.8-cabal.config
-    addons:
-      apt:
-        sources:
-        - hvr-ghc
-        packages:
-        - cabal-install-1.24
-        - ghc-8.0.2
-        - libgmp-dev
-    compiler: ! ': # ghc-8.0.2 cabal-1.24  servant-0.8-cabal.config'
-  - env: GHCVER=8.0.2 CABALVER=1.24 CABALCONFIG=servant-0.7-cabal.config
-    addons:
-      apt:
-        sources:
-        - hvr-ghc
-        packages:
-        - cabal-install-1.24
-        - ghc-8.0.2
-        - libgmp-dev
-    compiler: ! ': # ghc-8.0.2 cabal-1.24  servant-0.7-cabal.config'
-  - env: GHCVER=8.0.1 CABALVER=1.24 CABALCONFIG=swagger2-2.1-cabal.config
-    addons:
-      apt:
-        sources:
-        - hvr-ghc
-        packages:
-        - cabal-install-1.24
-        - ghc-8.0.1
-        - libgmp-dev
-    compiler: ! ': # ghc-8.0.1 cabal-1.24  swagger2-2.1-cabal.config'
-  - env: GHCVER=8.0.1 CABALVER=1.24 CABALCONFIG=servant-0.10-cabal.config
-    addons:
-      apt:
-        sources:
-        - hvr-ghc
-        packages:
-        - cabal-install-1.24
-        - ghc-8.0.1
-        - libgmp-dev
-    compiler: ! ': # ghc-8.0.1 cabal-1.24  servant-0.10-cabal.config'
-  - env: GHCVER=8.0.1 CABALVER=1.24 CABALCONFIG=servant-0.9-cabal.config
-    addons:
-      apt:
-        sources:
-        - hvr-ghc
-        packages:
-        - cabal-install-1.24
-        - ghc-8.0.1
-        - libgmp-dev
-    compiler: ! ': # ghc-8.0.1 cabal-1.24  servant-0.9-cabal.config'
-  - env: GHCVER=8.0.1 CABALVER=1.24 CABALCONFIG=servant-0.8-cabal.config
-    addons:
-      apt:
-        sources:
-        - hvr-ghc
-        packages:
-        - cabal-install-1.24
-        - ghc-8.0.1
-        - libgmp-dev
-    compiler: ! ': # ghc-8.0.1 cabal-1.24  servant-0.8-cabal.config'
-  - env: GHCVER=8.0.1 CABALVER=1.24 CABALCONFIG=servant-0.7-cabal.config
-    addons:
-      apt:
-        sources:
-        - hvr-ghc
-        packages:
-        - cabal-install-1.24
-        - ghc-8.0.1
-        - libgmp-dev
-    compiler: ! ': # ghc-8.0.1 cabal-1.24  servant-0.7-cabal.config'
-  - env: GHCVER=7.10.3 CABALVER=1.22 CABALCONFIG=swagger2-2.1-cabal.config
-    addons:
-      apt:
-        sources:
-        - hvr-ghc
-        packages:
-        - cabal-install-1.22
-        - ghc-7.10.3
-        - libgmp-dev
-    compiler: ! ': # ghc-7.10.3 cabal-1.22  swagger2-2.1-cabal.config'
-  - env: GHCVER=7.10.3 CABALVER=1.22 CABALCONFIG=swagger2-2.0-cabal.config
-    addons:
-      apt:
-        sources:
-        - hvr-ghc
-        packages:
-        - cabal-install-1.22
-        - ghc-7.10.3
-        - libgmp-dev
-    compiler: ! ': # ghc-7.10.3 cabal-1.22  swagger2-2.0-cabal.config'
-  - env: GHCVER=7.10.3 CABALVER=1.22 CABALCONFIG=servant-0.10-cabal.config
-    addons:
-      apt:
-        sources:
-        - hvr-ghc
-        packages:
-        - cabal-install-1.22
-        - ghc-7.10.3
-        - libgmp-dev
-    compiler: ! ': # ghc-7.10.3 cabal-1.22  servant-0.10-cabal.config'
-  - env: GHCVER=7.10.3 CABALVER=1.22 CABALCONFIG=servant-0.9-cabal.config
-    addons:
-      apt:
-        sources:
-        - hvr-ghc
-        packages:
-        - cabal-install-1.22
-        - ghc-7.10.3
-        - libgmp-dev
-    compiler: ! ': # ghc-7.10.3 cabal-1.22  servant-0.9-cabal.config'
-  - env: GHCVER=7.10.3 CABALVER=1.22 CABALCONFIG=servant-0.8-cabal.config
-    addons:
-      apt:
-        sources:
-        - hvr-ghc
-        packages:
-        - cabal-install-1.22
-        - ghc-7.10.3
-        - libgmp-dev
-    compiler: ! ': # ghc-7.10.3 cabal-1.22  servant-0.8-cabal.config'
-  - env: GHCVER=7.10.3 CABALVER=1.22 CABALCONFIG=servant-0.7-cabal.config
-    addons:
-      apt:
-        sources:
-        - hvr-ghc
-        packages:
-        - cabal-install-1.22
-        - ghc-7.10.3
-        - libgmp-dev
-    compiler: ! ': # ghc-7.10.3 cabal-1.22  servant-0.7-cabal.config'
-  - env: GHCVER=7.10.3 CABALVER=1.22 CABALCONFIG=servant-0.6-cabal.config
-    addons:
-      apt:
-        sources:
-        - hvr-ghc
-        packages:
-        - cabal-install-1.22
-        - ghc-7.10.3
-        - libgmp-dev
-    compiler: ! ': # ghc-7.10.3 cabal-1.22  servant-0.6-cabal.config'
-  - env: GHCVER=7.10.3 CABALVER=1.22 CABALCONFIG=servant-0.5-cabal.config
-    addons:
-      apt:
-        sources:
-        - hvr-ghc
-        packages:
-        - cabal-install-1.22
-        - ghc-7.10.3
-        - libgmp-dev
-    compiler: ! ': # ghc-7.10.3 cabal-1.22  servant-0.5-cabal.config'
-  - env: GHCVER=7.10.3 CABALVER=1.22 CABALCONFIG=servant-0.4-cabal.config
-    addons:
-      apt:
-        sources:
-        - hvr-ghc
-        packages:
-        - cabal-install-1.22
-        - ghc-7.10.3
-        - libgmp-dev
-    compiler: ! ': # ghc-7.10.3 cabal-1.22  servant-0.4-cabal.config'
-  - env: GHCVER=7.8.4  CABALVER=1.18 CABALCONFIG=servant-0.9-cabal.config
-    addons:
-      apt:
-        sources:
-        - hvr-ghc
-        packages:
-        - cabal-install-1.18
-        - ghc-7.8.4
-        - libgmp-dev
-    compiler: ! ': # ghc-7.8.4 cabal-1.18  servant-0.9-cabal.config'
-  - env: GHCVER=7.8.4  CABALVER=1.18 CABALCONFIG=servant-0.8-cabal.config
-    addons:
-      apt:
-        sources:
-        - hvr-ghc
-        packages:
-        - cabal-install-1.18
-        - ghc-7.8.4
-        - libgmp-dev
-    compiler: ! ': # ghc-7.8.4 cabal-1.18  servant-0.8-cabal.config'
-  - env: GHCVER=7.8.4  CABALVER=1.18 CABALCONFIG=servant-0.7-cabal.config
-    addons:
-      apt:
-        sources:
-        - hvr-ghc
-        packages:
-        - cabal-install-1.18
-        - ghc-7.8.4
-        - libgmp-dev
-    compiler: ! ': # ghc-7.8.4 cabal-1.18  servant-0.7-cabal.config'
-  - env: GHCVER=7.8.4  CABALVER=1.18 CABALCONFIG=servant-0.6-cabal.config
-    addons:
-      apt:
-        sources:
-        - hvr-ghc
-        packages:
-        - cabal-install-1.18
-        - ghc-7.8.4
-        - libgmp-dev
-    compiler: ! ': # ghc-7.8.4 cabal-1.18  servant-0.6-cabal.config'
-  - env: GHCVER=7.8.4  CABALVER=1.18 CABALCONFIG=servant-0.5-cabal.config
-    addons:
-      apt:
-        sources:
-        - hvr-ghc
-        packages:
-        - cabal-install-1.18
-        - ghc-7.8.4
-        - libgmp-dev
-    compiler: ! ': # ghc-7.8.4 cabal-1.18  servant-0.5-cabal.config'
-  - env: GHCVER=7.8.4  CABALVER=1.18 CABALCONFIG=servant-0.4-cabal.config
-    addons:
-      apt:
-        sources:
-        - hvr-ghc
-        packages:
-        - cabal-install-1.18
-        - ghc-7.8.4
-        - libgmp-dev
-    compiler: ! ': # ghc-7.8.4 cabal-1.18  servant-0.4-cabal.config'
-branches:
-  only:
-  - master
-before_cache:
-- rm -fv $HOME/.cabal/packages/hackage.haskell.org/build-reports.log
-- rm -fv $HOME/.cabal/packages/hackage.haskell.org/00-index.tar
+sudo: false
+
+git:
+  submodules: false  # whether to recursively clone submodules
+
 cache:
   directories:
-  - $HOME/.cabsnap
-  - $HOME/.cabal/packages
+    - $HOME/.cabal/packages
+    - $HOME/.cabal/store
+
+before_cache:
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/build-reports.log
+  # remove files that are regenerated by 'cabal update'
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/00-index.*
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/*.json
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/01-index.cache
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/01-index.tar
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/01-index.tar.idx
+
+matrix:
+  include:
+    - compiler: "ghc-7.8.4"
+    # env: TEST=--disable-tests BENCH=--disable-benchmarks
+      addons: {apt: {packages: [ghc-ppa-tools,cabal-install-head,ghc-7.8.4], sources: [hvr-ghc]}}
+    - compiler: "ghc-7.10.3"
+    # env: TEST=--disable-tests BENCH=--disable-benchmarks
+      addons: {apt: {packages: [ghc-ppa-tools,cabal-install-head,ghc-7.10.3], sources: [hvr-ghc]}}
+    - compiler: "ghc-8.0.2"
+    # env: TEST=--disable-tests BENCH=--disable-benchmarks
+      addons: {apt: {packages: [ghc-ppa-tools,cabal-install-head,ghc-8.0.2], sources: [hvr-ghc]}}
+
+before_install:
+ - HC=${CC}
+ - unset CC
+ - PATH=/opt/ghc/bin:/opt/ghc-ppa-tools/bin:$PATH
+ - PKGNAME='servant-swagger-ui'
+
+install:
+ - cabal --version
+ - echo "$(${HC} --version) [$(${HC} --print-project-git-commit-id 2> /dev/null || echo '?')]"
+ - BENCH=${BENCH---enable-benchmarks}
+ - TEST=${TEST---enable-tests}
+ - travis_retry cabal update -v
+ - sed -i 's/^jobs:/-- jobs:/' ${HOME}/.cabal/config
+ - rm -fv cabal.project.local
+ - "echo 'packages: .' > cabal.project"
+ - rm -f cabal.project.freeze
+ - cabal new-build -w ${HC} ${TEST} ${BENCH} --dep -j2
+ - cabal new-build -w ${HC} --disable-tests --disable-benchmarks --dep -j2
+
+# Here starts the actual work to be performed for the package under test;
+# any command which exits with a non-zero exit code causes the build to fail.
+script:
+ - if [ -f configure.ac ]; then autoreconf -i; fi
+ - rm -rf dist/
+ - cabal sdist # test that a source-distribution can be generated
+ - cd dist/
+ - SRCTAR=(${PKGNAME}-*.tar.gz)
+ - SRC_BASENAME="${SRCTAR/%.tar.gz}"
+ - tar -xvf "./$SRC_BASENAME.tar.gz"
+ - cd "$SRC_BASENAME/"
+## from here on, CWD is inside the extracted source-tarball
+ - rm -fv cabal.project.local
+ - "echo 'packages: .' > cabal.project"
+ # this builds all libraries and executables (without tests/benchmarks)
+ - rm -f cabal.project.freeze
+ - cabal new-build -w ${HC} --disable-tests --disable-benchmarks
+
+ - if [ ! $HC = "ghc-8.0.1" ]; then UNLESSGHC802=true; fi
+ - if [ ! $HC = "ghc-7.8.4" ]; then UNLESSGHC708=true; fi
+
+ - $UNLESSGHC802 cabal new-build -w ${HC} --disable-tests --disable-benchmarks '--constraint=servant==0.4.*'
+ - $UNLESSGHC802 cabal new-build -w ${HC} --enable-tests  --disable-benchmarks '--constraint=servant==0.4.*'
+
+ - $UNLESSGHC802 cabal new-build -w ${HC} --disable-tests --disable-benchmarks '--constraint=servant==0.5.*'
+ - $UNLESSGHC802 cabal new-build -w ${HC} --enable-tests  --disable-benchmarks '--constraint=servant==0.5.*'
+
+ - $UNLESSGHC802 cabal new-build -w ${HC} --disable-tests --disable-benchmarks '--constraint=servant==0.6.*'
+ - $UNLESSGHC802 cabal new-build -w ${HC} --enable-tests  --disable-benchmarks '--constraint=servant==0.6.*'
+
+ -               cabal new-build -w ${HC} --disable-tests --disable-benchmarks '--constraint=servant==0.7.*'
+ -               cabal new-build -w ${HC} --enable-tests  --disable-benchmarks '--constraint=servant==0.7.*'
+
+ -               cabal new-build -w ${HC} --disable-tests --disable-benchmarks '--constraint=servant==0.8.*'
+ -               cabal new-build -w ${HC} --enable-tests  --disable-benchmarks '--constraint=servant==0.8.*'
+
+ -               cabal new-build -w ${HC} --disable-tests --disable-benchmarks '--constraint=servant==0.9.*'
+ -               cabal new-build -w ${HC} --enable-tests  --disable-benchmarks '--constraint=servant==0.9.*'
+
+ -               cabal new-build -w ${HC} --disable-tests --disable-benchmarks '--constraint=servant==0.10.*'
+ -               cabal new-build -w ${HC} --enable-tests  --disable-benchmarks '--constraint=servant==0.10.*'
+
+ # this builds all libraries and executables (including tests/benchmarks)
+ # - rm -rf ./dist-newstyle
+ - cabal new-build -w ${HC} ${TEST} ${BENCH}
+
+ # there's no 'cabal new-test' yet, so let's emulate for now
+ - TESTS=( $(awk 'tolower($0) ~ /^test-suite / { print $2 }' *.cabal) )
+ - if [ "$TEST" != "--enable-tests" ]; then TESTS=(); fi
+ - shopt -s globstar;
+   RC=true; for T in ${TESTS[@]}; do echo "== $T ==";
+   if dist-newstyle/build/**/$SRC_BASENAME/**/build/$T/$T; then echo "= $T OK =";
+   else echo "= $T FAILED ="; RC=false; fi; done; $RC
+
+# EOF
+
+branches:
+  only:
+    - master
